name: Deploy Package to PyPi Test Repo
on:
  push:
    branches:
      - feature

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PyPi Package Upload Dependencies
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine

      - name: Build Package
        run: python3 -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/